cbv_folder/cbv_project/cbv_app/urls.py
from . import views
from django.urls import path

from .views import MovieListView, MovieDetailView, MovieUpdateView, MovieDeleteView

app_name = 'cbv_app'
urlpatterns = [

    path('', views.home, name='home'),
    path('cbvhome', MovieListView.as_view(), name='cbvhome'),
    path('detail/<int:pk>/', MovieDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', MovieUpdateView.as_view(), name='update'),
    path('movie/<int:pk>/delete/', MovieDeleteView.as_view(), name='delete'),
]

cbv_folder/cbv_project/cbv_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cbv_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cbv_app.urls')),
    path('search/', include('search_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cbv_folder/cbv_project/search_app/urls.py
from . import views
from django.urls import path
from cbv_app.views import MovieListView, MovieDetailView

app_name = 'search_app'
urlpatterns = [

    path('', views.searchResult, name='searchResult'),
    path('detail/<int:pk>/', MovieDetailView.as_view(), name='detail'),
]

cbv_folder/cbv_project/cbv_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Movie(models.Model):
    movieName = models.CharField(max_length= 300)
    moviePriority = models.IntegerField()
    movieImg = models.ImageField(upload_to='task_img')
    movieDate = models.DateField()
    movieInfo = models.TextField()

    def __str__(self):
        return self.movieName

cbv_folder/cbv_project/search_app/models.py
from django.db import models

# Create your models here.

cbv_folder/cbv_project/cbv_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView, DeleteView
from cbv_app.models import Movie


# Create your views here.
#sample_test
def home(request):
    movieHomeObj = Movie.objects.all()
    if request.method == 'POST':
        movie_name = request.POST.get('movie_name', '')
        movie_priority = request.POST.get('movie_priority', '')
        movie_date = request.POST.get('movie_date', '')
        movie_info = request.POST.get('movie_info', '')
        movie_img = request.FILES['movie_img']

        movieHome = Movie(movieName= movie_name, moviePriority= movie_priority, movieImg= movie_img, movieDate= movie_date, movieInfo= movie_info)
        movieHome.save()
    return render(request, 'index.html', {'movieHomeObj': movieHomeObj})

class MovieListView(ListView):
    model = Movie
    template_name = 'index.html'
    context_object_name = 'movieHomeObj'

class MovieDetailView(DetailView):
    model = Movie
    template_name = 'detail.html'
    context_object_name = 'movieHomeObj'

class MovieUpdateView(UpdateView):
    model = Movie
    template_name = 'update.html'
    fields = ('movieName', 'moviePriority', 'movieImg', 'movieDate', 'movieInfo')
    context_object_name = 'movieDetailObj'
    success_url = reverse_lazy('cbv_app:detail')

    def get_success_url(self):
        return reverse_lazy('cbv_app:detail', kwargs={'pk': self.object.id})

class MovieDeleteView(DeleteView):
    model = Movie
    template_name = 'delete.html'
    success_url = reverse_lazy('cbv_app:cbvhome')

cbv_folder/cbv_project/search_app/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from cbv_app.models import Movie
from django.db.models import Q



def searchResult(request):
    searchedMovies = None
    query = None
    if "q" in request.GET:
        query = request.GET.get('q')
        searchedMovies = Movie.objects.all().filter(Q(movieName__contains=query)| Q(movieInfo__contains=query))
    return render(request, 'search.html', {'query': query, 'searchedMovies': searchedMovies})


class MovieDetailView(DetailView):
    model = Movie
    template_name = 'detail.html'
    context_object_name = 'movieDetailObj'

cbv_folder/cbv_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
   <div>
       {% include 'header.html' %}
   </div>

   <div>
       {% block content %}
       {% endblock %}
   </div>

   <div>
       {% include 'footer.html' %}
   </div>
   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
   <script src="{% static 'js/popper.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

cbv_folder/cbv_project/templates/delete.html
{% extends 'base.html' %}

  {% block content %}



    <div class="container delete_container">
         <div class="row">
             <div class="card delete_card_div">
                 <div class="card-titile main_delete_card_title">
                     <h5>Are you sure you want to delete this film?</h5>
                     <div class="card-body">
                         <div class="card-detail delete_card_detail" style="width= 18rem;">
                            <img src="{{movie.movieImg.url}}" class="delete_card_img" alt="...">
                               <h5 class="card-title delete_card_title">{{movie.movieName}}</h5>
                         </div>
                         <div class="row delete_confirm_row">
                            <form method="POST" enctype="multipart/form-data" action="{% url 'cbv_app:delete' movie.id %}">
                             {% csrf_token %}
                                <input type="hidden" name="next" value="{% url 'cbv_app:cbvhome' %}">
                               <button type="submit" class="btn btn-danger" name="delete">Delete</button>
                               <a href="{% url 'cbv_app:cbvhome' %}" class="btn btn-primary">Back To Home</a>
                            </form>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>

{% endblock %}

cbv_folder/cbv_project/templates/detail.html
{% extends 'base.html' %}

  {% block metadescription %}
     {{ movieDetailObj.movieName | truncatewords:155 }}
  {% endblock %}

  {% block title %}
     {% if movieHomeObj %}
        {{ movieHomeObj.movieName }}
     {% endif %}
  {% endblock %}

   {% block content %}
      <div class="container detail_top_container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div class="card shadow text-center text-justify card-details" style="">
                  <img src="{{movieHomeObj.movieImg.url}}" class="card-img-top-detail" alt="...">
                  <div class="card-body card-body-details">
                     <h5 class="card-title">{{movieHomeObj.movieName}}</h5>
                     <p class="card-text">{{movieHomeObj.movieDate}}</p>
                  </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <h3>Movie Description</h3>
                <p class="card-text text-justify">{{movieHomeObj.movieInfo }}</p>
                <div class="mx-auto text-center text-justify details_icons_div">
                   <a href="{% url 'cbv_app:cbvhome' %}"><i class="fa fa-arrow-circle-left fa-1x detail_page_icons"></i></a>
                   <a href="{% url 'cbv_app:update' movieHomeObj.id %}"><i class="fa fa-plus-circle fa-1x detail_page_icons"></i></a>
                   <a href="{% url 'cbv_app:delete' movieHomeObj.id %}"><i class="fa fa-trash fa-1x detail_page_icons"></i></a>
                   <a href="{% url 'cbv_app:cbvhome' %}"><i class="fa fa-home fa-1x detail_page_icons"></i></a>
                </div>
            </div>
        </div>
      </div>

   {% endblock %}

cbv_folder/cbv_project/templates/footer.html
{% load static %}
<footer class="text-center text-white navbar-fixed-bottom my_footer">
    <section id="d-flex justify-content-between p-4 my_foot_section" style="background-color: #B0C4DE;">
      <div class="me-5">
        <span>Get connected with us on social networks:</span>
      </div>
      <div>
        <a href="http://www.facebook.com" class="text-white me-4">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="http://www.twitter.com" class="text-white me-4">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="http://www.google.com" class="text-white me-4">
          <i class="fab fa-google"></i>
        </a>
        <a href="http://www.instagram.com" class="text-white me-4">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="http://www.linkedin.com" class="text-white me-4">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="http://www.github.com" class="text-white me-4">
          <i class="fab fa-github"></i>
        </a>
      </div>
    </section>
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold">HoLLywOOd HuB</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto" style="width: 140px; background-color: #FFFFFF; height: 5px"/>
            <p>
              Here you can use rows and columns to organize your footer
              content. Lorem ipsum dolor sit amet, consectetur adipisicing
              elit.
            </p>
          </div>

          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold">Products</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 90px; background-color: #FFFFFF; height: 5px"
                />
            <p>
              <a href="#!" class="text-white foot_pro_a">Web Series</a>
            </p>
            <p>
              <a href="#!" class="text-white foot_pro_a">TV Shows</a>
            </p>
            <p>
              <a href="#!" class="text-white foot_pro_a">Music</a>
            </p>
            <p>
              <a href="#!" class="text-white foot_pro_a">Interviews</a>
            </p>
          </div>

          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold">Useful links</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 115px; background-color: #FFFFFF; height: 5px"
                />
            <p>
              <a href="#!" class="text-white foot_pro_a">Your Account</a>
            </p>
            <p>
              <a href="#!" class="text-white foot_pro_a">Become an Affiliate</a>
            </p>
            <p>
              <a href="#!" class="text-white foot_pro_a">Shipping</a>
            </p>
            <p>
              <a href="#!" class="text-white foot_pro_a">Help</a>
            </p>
          </div>

          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 70px; background-color: #FFFFFF; height: 5px"
                />
            <p><i class="fas fa-home mr-3"></i> World, TVL 10012, World</p>
            <p><i class="fas fa-envelope mr-3"></i> hollywoodhubinfo@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
        </div>
      </div>
    </section>
    <div class="text-center foot_p-3">
      © 2023 Copyright:
      <a class="text-white" href="https://hollywoodhub.com/">hollywoodhub.com</a>
    </div>
</footer>

cbv_folder/cbv_project/templates/header.html
{% load static %}
<div class="fluid-container">
    <div class="row">
        <div class="col-md-12">
            <div class="banner shadow">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="#"><h3>HoLLywOOd HuB</h3></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link active link-hover" aria-current="page" href="{% url 'cbv_app:cbvhome' %}"><i class="fa fa-home fa-2x"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#" style="color: white;">Pricing</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" style="color: white; font-size: 18px;" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Products
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="#">Movies</a></li>
                                        <li><a class="dropdown-item" href="#">Web Series</a></li>
                                        <li><a class="dropdown-item" href="#">Interviews</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="#">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="#">Contact Us</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: white;" href="#">Review</a>
                                </li>
                            </ul>
                            <form class="d-flex ml-auto" action="{% url 'search_app:searchResult' %}" method="get">
                                <input class="form-control me-2" type="search" placeholder="Search movie" name="q" aria-label="Search">
                                <button class="btn btn-outline-info custom_search_icon" type="submit"><i class="fa fa-search custom_search_ico"></i></button>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>

cbv_folder/cbv_project/templates/index.html
{% extends 'base.html' %}
  {% load static %}
  {% block metadescription %}
     Index - hollywood hub
  {% endblock %}

  {% block title %}
     hollywood hub
  {% endblock %}

  {% block content %}
      <div class="container">
         <div class="row mx-auto">
             <div class="col-9 col-sm-12 col-md-6 xol-lg-6">
                 <form method="POST" class="p-3 shadow" enctype="multipart/form-data">
                     {% csrf_token %}
                     <input class="form-control" type="text" name="movie_name" placeholder="Enter the movie name">
                     <input class="form-control" type="text" name="movie_priority" placeholder="Enter the movie priority">
                     <input class="form-control" type="date" name="movie_date" placeholder="Enter the movie date">
                     <input class="form-control" type="text" name="movie_info" placeholder="Enter the movie details">
                     <input class="form-c" type="file" name="movie_img"><br>
                     <button class="btn-add btn-primary">Add</button>
                 </form>
             </div>
             <div class="col-12 col-sm-12 col-md-6 xol-lg-6">
                 <img src="{% static 'img/hollywood.jpg' %}" class="hollywood-img shadow" alt="">
             </div>
         </div>
      </div>
      <div class="container">
          <div class="row mx-auto">
              {% for i in movieHomeObj %}
              <div class="col-9 col-sm-12 col-md-4 xol-lg-4 index_list_div">
                    <div class="card shadow">
                      <a href="{% url 'cbv_app:detail' i.id %}"><img src="{{i.movieImg.url}}" class="card-img-top" alt="..."></a>
                      <div class="card-body">
                         <h5 class="card-title">{{i.movieName}}</h5>
                         <a href="{% url 'cbv_app:detail' i.id %}" class="btn btn-primary more_detail_btn">More Details</a>
                      </div>
                    </div>
              </div>
              {% endfor %}
          </div>
      </div>

  {% endblock %}

cbv_folder/cbv_project/templates/search.html
{% extends 'base.html' %}

  {% block metadescription %}
      We have plenty of options for you
  {% endblock %}

  {% block title %}
     {% if movieDetailObj %}
        search
     {% endif %}
  {% endblock %}

  {% block content %}
      <div class="container update_container text-justify">
          <div>
              <p class="text-center serched_text">You have searched for <b>'{{query}}'</b></p>
          </div>
          <div class="row mx-auto">
              {% for searchedmovie in searchedMovies %}
              <div class="col-9 col-sm-12 col-md-3 xol-lg-4">
                <div class="card shadow searched_card" style="width: 18rem; height: 330px">
                  <a href="{% url 'search_app:detail' searchedmovie.id %}"><img class="movie_searched_detail_pic" src="{{searchedmovie.movieImg.url}}" alt="{{searchedmovie.movieName}}"></a>
                 <div class="card-body search_card_body">
                   <h5>{{ searchedmovie.movieName }}</h5>
                 </div>
                </div>
              </div>
              {% empty %}
                 <div class="container search_text_empty text-justify">
                     <p class="text-center"> 0 Results found.</p>
                 </div>
              {% endfor %}
          </div>
          <div class="mx-auto text-center text-justify details_icons_div">
             <a href="{% url 'cbv_app:cbvhome' %}"><i class="fa fa-arrow-left fa-1x"></i></a>
             <a href="{% url 'cbv_app:cbvhome' %}"><i class="fa fa-home fa-1x"></i></a>
         </div>
      </div>
  {% endblock %}

cbv_folder/cbv_project/templates/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container update_container text-justify">
    <div class="row mx-auto">
      <div class="col-12 col-md-6 mb-4">
        <div class="card update_card text-center text-justify">
          <div class="card-title update_card-title">
            <h5>Movie Update</h5>
          </div>
          <div class="card-body update_card_body">
            <form class="p-3 shadow update_form" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{form.as_p}}
              <button class="btn-add btn-primary btn_add_update">Add</button>
            </form>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-6 mb-4">
        <div class="card text-center text-justify updated_image_card_body">

          <div class="card-body_current_img">
            <img src="{{movieDetailObj.movieImg.url}}" class="card-img-top_updated" alt="...">
            <div class="card-body_current_img_titile">
              <p>Current Image</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mx-auto text-center text-justify details_icons_div">
      <a href="{% url 'cbv_app:cbvhome' %}"><i class="fa fa-arrow-left fa-1x"></i></a>
      <a href="{% url 'cbv_app:update' movieDetailObj.id %}"><i class="fa fa-plus-circle fa-1x"></i></a>
      <a href="{% url 'cbv_app:delete' movieDetailObj.id %}"><i class="fa fa-trash fa-1x"></i></a>
      <a href="{% url 'cbv_app:cbvhome' %}"><i class="fa fa-home fa-1x"></i></a>
    </div>
  </div>
{% endblock %}